"""check for pending changes

Revision ID: 53de116aaf09
Revises: b4e7a2d9c1f3
Create Date: 2026-02-16 16:59:00.713620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53de116aaf09'
down_revision: Union[str, Sequence[str], None] = 'b4e7a2d9c1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('account', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'admins', ['account'])
    op.alter_column('shoe_images', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shoe_images', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'account')
    # ### end Alembic commands ###
