"""refactor_soft_delete_and_order_completion

Revision ID: 748dbec5516c
Revises: a3d9d962a8a6
Create Date: 2026-03-27 22:17:30.794540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748dbec5516c'
down_revision: Union[str, Sequence[str], None] = 'a3d9d962a8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_orders')
    op.add_column('client_orders', sa.Column('isCompleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('client_orders', sa.Column('dateCompleted', sa.DateTime(), nullable=True))
    op.add_column('client_orders', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('clients', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('companies', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('payment_summaries', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('payment_summaries', 'original_order_id')
    op.add_column('payment_transactions', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('persons', sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'isDeleted')
    op.drop_column('payment_transactions', 'isDeleted')
    op.add_column('payment_summaries', sa.Column('original_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('payment_summaries', 'isDeleted')
    op.drop_column('companies', 'isDeleted')
    op.drop_column('clients', 'isDeleted')
    op.drop_column('client_orders', 'isDeleted')
    op.drop_column('client_orders', 'dateCompleted')
    op.drop_column('client_orders', 'isCompleted')
    op.create_table('completed_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('size', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mold', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('heel_size', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('heel_type', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('has_platform', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_slingback', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_buckle', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('original_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('completed_orders_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('completed_orders_pkey'))
    )
    # ### end Alembic commands ###
