"""link completed_orders to client

Revision ID: b223811a449e
Revises: f777e61c7742
Create Date: 2026-03-26 23:39:24.788267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b223811a449e'
down_revision: Union[str, Sequence[str], None] = 'f777e61c7742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'completed_orders', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_orders', type_='foreignkey')
    # ### end Alembic commands ###
