"""add completed_orders

Revision ID: f777e61c7742
Revises: 37ba4a2bf04d
Create Date: 2026-03-26 23:34:23.174313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f777e61c7742'
down_revision: Union[str, Sequence[str], None] = '37ba4a2bf04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('mold', sa.String(length=20), nullable=False),
    sa.Column('heel_size', sa.String(length=5), nullable=False),
    sa.Column('heel_type', sa.String(length=15), nullable=False),
    sa.Column('has_platform', sa.Boolean(), nullable=False),
    sa.Column('has_slingback', sa.Boolean(), nullable=False),
    sa.Column('has_buckle', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('client_orders', 'heel_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('client_orders', 'is_zero_balance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shoe_catalog', 'is_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shoe_catalog', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shoe_catalog', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('shoe_catalog', 'is_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('client_orders', 'is_zero_balance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('client_orders', 'heel_type',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_table('completed_orders')
    # ### end Alembic commands ###
